spring:
  application:
    name: server-daichao
  profiles:
    active: dev

  # 数据库的基本配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mytest

    #配置连接池
  #    type: com.alibaba.druid.pool.DruidDataSource

  # JPA配置
  jpa:
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql

  data:
    redis:
      host: "localhost"
      port: 6379
      database: 0
      # 连接超时
      connect-timeout: 5s
      # 读超时
      timeout: 5s

      # Lettuce 客户端的配置
      lettuce:
        # 连接池配置
        pool:
          # 最小空闲连接
          min-idle: 0
          # 最大空闲连接
          max-idle: 8
          # 最大活跃连接
          max-active: 8
          # 从连接池获取连接 最大超时时间，小于等于0则表示不会超时
          max-wait: -1ms

logging:
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss.SSS}) %green([%thread]) %blue([%-4level]) %cyan(%logger{30}:%line) %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%-4level] %logger{30}:%line %msg%n"
  logback:
    rolling policy:
      max-file-size: 10MB
  file:
    path: ./logs